spring.application.name=recommendation-service

server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Distributed Tracing Configuration (Micrometer + Zipkin)
management.tracing.sampling.probability=${TRACING_SAMPLING_PROBABILITY:1.0}
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}


spring.datasource.url=jdbc:mysql://localhost:3306/recommendation_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect