spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=2000
eureka.server.response-cache-update-interval-ms=1000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always